site_name: Go Events REST API
site_description: Documentation for the Go Events REST API â€“ built with Gin, JWT, and SQLite.
site_author: shyamhande
repo_url: https://github.com/shyam-hande/golang-rest
repo_name: shyam-hande/golang-rest

docs_dir: docs/techdocs

nav:
  - Home: index.md
  - API Reference: api.md
  - Testing: testing.md

theme:
  name: material

plugins:
  - techdocs-core
